NO_LEDS: 500
LAYOUT: 3d
FPS: 60
BRIGHTNESS: 0
CAMS:
  # List cameras - can either be an index or a url
  A:
    URL: http://172.32.1.225:8080/?action=snapshot
    ROTATE: 270
SCAN:
  TYPE: 3d-spinning-manual
  ANGLES:
    - 0
    - 90
    - 180
    - 270